#!/usr/bin/perl

use MP3::Tag;

my %hashy;
my $id = 0;
open(FILES, "< $ENV{HOME}/foo.m3u") or die ($!);

my $time = time();
my @foo = <FILES>;
foreach (@foo) {
	next if (m/^#/);
	chomp;

	my $foo = $_;

	my $t = time() - $time;
	printf("[%d / %.2f/sec / %.2f%%] %s\n",
			 $t, 
			 $id / ($t + .0000001),
			 $id / @foo, 
			 substr($foo,0,50));
	my $tag = MP3::Tag->new($_);
	my ($title, $track, $artist, $album, $comment, $year, $genre) = $tag->autoinfo();

	$hashy->{$id} = {
		title => $title,
		artist => $artist,
		album => $album
	};

	$id++;
}
