#!/usr/bin/perl

use MP3::Tag;
use Storable;

my %hashy;
my $id = 0;
open(FILES, "< $ENV{HOME}/foo.m3u") or die ($!);

my $time = time() - 1;
my @foo = <FILES>;
foreach (@foo) {
	next if (m/^#/);
	chomp;

	my $foo = $_;

	my $t = time() - $time;
	printf("[%d / %.2f/sec / %.2f%%] %s\n",
			 $t, 
			 $id / $t),
			 $id / @foo, 
			 substr($foo,0,50));
	my $tag = MP3::Tag->new($_);
	my ($title, $track, $artist, $album, $comment, $year, $genre) = $tag->autoinfo();

	$hashy->{$id} = {
		title => $title,
		artist => $artist,
		album => $album
	};

	$id++;
	$tag = undef;
}


print "ALL DONE!!!\n";
print "Took " . (time() - $time) . " seconds\n\n";

$time = time();
print "Storing...\n";
store(\%hashy, $ENV{HOME} . ".pimp/tags");
print "Done - took " . (time() - $time) . " seconds\n";
