#!/usr/bin/perl

use Audio::Mad qw(:all);
use Audio::Ao qw(:all);
use IO::Select;
use IO::Handle;
use Socket;
use Symbol;
use URI;

my $stream   = new Audio::Mad::Stream();
my $frame    = new Audio::Mad::Frame();
my $synth    = new Audio::Mad::Synth();
my $timer    = new Audio::Mad::Timer();
my $resample = new Audio::Mad::Resample(44100, 22050);
my $dither   = new Audio::Mad::Dither();

my $fd = Symbol::gensym();
print "Arg: " . $ARGV[0] . "\n";
if (defined($ARGV[0])) {
	my $file = $ARGV[0];
	if ($file =~ m!^http:\/\/!) {
		#my $u = URI->new("http://69.56.169.210:8080/stream");
		my $u = URI->new($file);

		$PORT = $u->port();
		$HOST = $u->host();
		$PATH = $u->path();


CONNECT:
		socket($fd, PF_INET, SOCK_STREAM, getprotobyname('tcp')) or die("socket(): $!");
		connect($fd, sockaddr_in($PORT, inet_aton($HOST))) or die("connect(): $!");

		$fd->autoflush(1);

		print $fd "GET $PATH HTTP/1.0\n\n";
		print "Connected\n";

		chomp(my $resp = <$fd>);
		my %headers;
		print "$resp\n";

		while (<$fd>) {
			chomp();
			s/
//;
			last if (m/^\s*$/);
			m/(\S+):\s*(.+)\s*/;
			$headers{$1} = $2;
			print "[$1] $2\n";

			#print "$_\n";
		}

		print "\n";

		if ($resp =~ m/^\S+\s+302/) {
			print "(" . $headers{"Location"} . ")\n";
			my $u = URI->new($headers{"Location"});

			$PORT = $u->port();
			$HOST = $u->host();
			$PATH = $u->path();
			close($fd);
			goto CONNECT;
		}

	} elsif ($file =~ m!^/!) {
		open($fd,"< $file") or die ("Failed trying to open $file\n$!");
	}
} else {
	print "Reading from stdin\n";
	$fd = \*STDIN;
	#open($fd, "<&STDIN") or die ("Failed dup()\n$!");
}
print "DONE\n";

my $select = IO::Select->new($fd);
my $BUFSIZE = 8192;

my $buffer;
my $tbytes = 0;


my $time = time();
#if (sysread($fd,$buffer,$BUFSIZE,0)) {
	#$tbytes += length($buffer);
	#print "Buffer read OK [$tbytes bytes read so far]\n";
#} else {
	#die("Unable to read from $fd!?\n$!\n");
#}
#$stream->buffer($buffer);

initialize_ao;


my $device = open_live(default_driver_id(), 16, 22050, 2, is_big_endian(), {});
die("Unable to open sound device\n") unless defined($device);
my ($fsize);

print "Prebuffering...\n";
while (length($buffer) < 65536) {
	sysread($fd, $buffer, $BUFSIZE, length($buffer));
}

FOO:
while (1) {
	#if ($select->can_read()) {
		if (length($buffer) < 65536) {
			my $foo = sysread($fd, $buffer, $BUFSIZE, length($buffer));
			if ($foo) {
				#print "$foo = sysread()\n";
			}
		}
	#}

	if ($frame->decode($stream) == -1) {
		next if ($stream->err_ok());
		if ($stream->error == MAD_ERROR_BUFLEN || 
			 $stream->error == MAD_ERROR_BUFPTR) {

			# Make sure we don't drop the last frame fragment
			#my $partial = substr($buffer, $stream->next_frame(), $BUFSIZE);
			$buffer = substr($buffer, $stream->next_frame());
			#$buffer = substr($buffer, $stream->next_frame() + $BUFSIZE);
			print "Buffer length: " . length($buffer) . " / " . length($partial) ."\n";

			#last if (sysread($fd, $buffer, $BUFSIZE - length($buffer), length($buffer)) == 0);

			$tbytes += length($buffer);
			$stream->buffer($buffer);
			my $b = $tbytes / (time() - $time) if (time() - $time > 0);
			print "Buffer read OK [$tbytes total | $b bytes/sec]\n";

			redo FOO;
		}

		print STDERR "Fatal error\n";
		last;
	}
	$fsize = ($stream->next_frame() - $stream->this_frame()) unless defined($fsize);
	if ($fsize - 10 > ($stream->next_frame() - $stream->this_frame())) {
		$oldbuf = substr($buffer,$stream->this_frame());
	}
	$synth->synth($frame);
	my $pcm = $dither->dither($synth->samples());

	play($device,$pcm,length($pcm));
}
#if (read($fd,$buffer,$BUFSIZE,0)) {
	#print "Buffer read OK [$tbytes bytes read so far]\n";
	#$buffer = $oldbuf . $buffer;
	#$oldbuf = undef;
	#$stream->buffer($buffer);
	#$stream->sync();
	#$tbytes += length($buffer);
	#goto FOO;
#}

close_ao($device);
shutdown_ao;
