#ifndef _GROK_MATCHCONF_FILTER_
#define _GROK_MATCHCONF_FILTER_

enum matchconf_filter_type {
  VALUE_LINE,
  VALUE_MATCH,
  VALUE_JSON,
  VALUE_START,
  VALUE_END,
  VALUE_LENGTH,
};

#ifndef _GPERF_
struct strfilter {
  const char *str;
  int code;
};
#endif

/* this function is generated by gperf */
const struct strfilter *patname2enum(const const char *str, unsigned int len);

#endif /* _GROK_MATCHCONF_FILTER_ */
