#!/bin/sh

rungrok() {
  perl ../grok "$@"
}

try() {
  OUTPUT=`mktemp /tmp/logwatcher.test.XXXXX`
  rungrok -f conf/$1 > $OUTPUT 2> /dev/null
  #perl ../grok -f conf/$1 > $OUTPUT 2> /dev/null
  compare $OUTPUT output/$1
  EXITCODE=$?
  [ "$EXITCODE" -eq 0 ] && echo "Test OK: $1" || echo "Test failed: $1"
  return $EXITCODE
}

try_self() {
  # $1 =~ should be test_*.sh
  SELF=$1
  TESTNAME=`echo "$SELF" | sed -e 's/^test_//; s/\.sh$//;'`
  try $TESTNAME
}

compare() {
  diff -u $1 $2 > /tmp/output
  return $?
}
